//! # Automatically Generate Structs From Metadata Schema
//!
//! This build script generates Rust type definitions from the JSON Schema
//! before every build from the schema is located at
//! `metadata/metadata.schema.json`. The generated code is written to
//! `metadata/metadata_schema.rs`.
//!
//! ## Purpose
//!
//! - Ensure the Rust data structures used in this crate stay in sync with the
//!   JSON schema.
//! - Avoid manual type definition updates when the schema changes.
//!
//! ## How It Works
//!
//! 1. Reads the JSON Schema from `metadata/metadata.schema.json`.
//! 2. Parses it into a `schemars::schema::RootSchema`.
//! 3. Uses [`typify`] with [`TypeSpace`] to generate Rust types, enabling
//!    the `struct_builder` option for builder-pattern struct construction.
//! 4. Formats the generated Rust code using [`prettyplease`].
//! 5. Writes the result to `metadata/metadata_schema.rs`.

use std::{fs, path::Path};

use typify::{TypeSpace, TypeSpaceSettings};

fn main() {
    let content = std::fs::read_to_string("metadata/metadata.schema.json").unwrap();
    let schema = serde_json::from_str::<schemars::schema::RootSchema>(&content).unwrap();

    let mut type_space = TypeSpace::new(TypeSpaceSettings::default().with_struct_builder(true));
    type_space.add_root_schema(schema).unwrap();

    // Generate the structs and documentation of metadata_schema.rs.
    let file_contents =
        prettyplease::unparse(&syn::parse2::<syn::File>(type_space.to_stream()).unwrap());
    let documentation = r#"//! # Automatically Generated Metadata Schema
//!
//! This file is automatically generated by build.rs and contains the structs
//! generated from metadata.schema.json. Do not edit.

"#;
    let final_contents = format!("{}{}", documentation, file_contents);

    // Add file contents to metadata_schema.rs.
    let mut out_file = Path::new("metadata").to_path_buf();
    out_file.push("metadata_schema.rs");
    fs::write(out_file, final_contents).unwrap();
}
